project:
  type: website

website:
  title: "CDMetaPOP"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Introduction"
        href: introduction.qmd
      # - text: "Input Files"        
      #   menu:
      #     - text: "classVars"
      #       href: input_files/classVars.qmd
      #     - text: "patchVars"
      #       href: input_files/patchVars.qmd
      #     - text: "popVars"
      #       href: input_files/popVars.qmd
      #     - text: "runVars"
      #       href: input_files/runVars.qmd
      - text: "Run CDMetaPOP"
        href: run_cdmetapop.qmd
      - text: "cdmetapopR functions vignette"
        href: functions.qmd
        menu:
          - text: "age_plus_one_plot"
            href: functions/age_plus_one_plot.qmd
          - text: "age_structure_proportions"
            href: functions/age_structure_proportions.qmd
          - text: "alleles_by_year"
            href: functions/alleles_by_year.qmd
          - text: "births"
            href: functions/births.qmd
            

              
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

