project:
  type: website

website:
  title: "CDMetaPOP"
  navbar:
    left:
      - text: "Home"
        href: home.qmd
      - text: "Tutorials"
        menu:
          - text: "---"
          - text: "Install CDMetaPOP"
            href: install.qmd
          - text: "---"
          - text: "Python"
          - text: "  CDMetaPOP with Python Tutorial"
            href: python/python_tutorial.qmd
          - text: "---"
          - text: "R"
          - text: "Introduction to cdmetapopR"
            href: cdmetapopr/cdmetapopr_tutorial.qmd
          - text: "  Input files with Shiny Apps"
            href: cdmetapopr/cdmetapopr_shinyApps.qmd
          - text: "  Input files with Wrapper"
            href: cdmetapopr/cdmetapopr_wrapper.qmd
          - text: "  Outputs Vignette"
            href: cdmetapopr/cdmetapopr_output_vignette.qmd
      - text: "Publications"
        href: about.qmd
            

              
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

