---
title: "Introduction"
---

Here you will find the basic instructions to start a simulation with cdmetapop.R.

Let's start with a **suggestion** on how to arrange your files, an example of how you could arrange your data directory structure:

```         
data/
├── runVars.csv
├── popvars/
│   └── popVars.csv
├── patchvars/
│   └── patchVars.csv
├── classvars/
│   └── classVars.csv
├── genes/
│   └── allelefrequencies.csv
├── cdmats/
│   ├── cdmat1.csv
│   ├── cdmat2.csv
│   └── cdmat3.csv
└── otherfiles/
    ├── correlation_matrix1.csv
    └── correlation_matrix2.csv
```

CDMetaPOP can simulate very complex systems but you can get started with a very simple template. This platform and tutorial are meant to help you get acquainted with the basic functions without having to deal with changing too many parameters at once. It will help you build the basic files needed to run CDMetaPOP and give you some tips along the way.

The basic files you need are:

1.  **classVars.csv**: defines parameters related to the individuals according to their ages.

2.  **patchVars.csv:** defines the parameters related to your patches (sites).

3.  **popVars.csv:** defines several parameters that relate to the population as a whole.

4.  **runVars.csv:** defines the basic parameters of your simulation (for example how many Monte Carlo runs).

Although it may be counterintuitive, it is suggested to start preparing your files in the order given, as the runVars.csv requires to define a popVars.csv, which in turn designates both patchVars.csv and classVars.csv files.

Additional files can include distance matrices to guide individual movement and genetic files to initialize population genetic structure.

For more detailed instructions you can refer to CDMetaPOP manual and several publications:

1.  Manual

2.  bla

3.  blabla

4.  blablabla
